package com.vgretailersdk

data class RegisterWarrantyRequest(
    val nameTitle: String,
    val contactNo: String,
    val name: String,
    val email: String,
    val currAdd: String,
    val alternateNo: String,
    val state: String,
    val district: String,
    val city: String,
    val landmark: String,
    val pinCode: String,
    val dealerName: String,
    val dealerAdd: String,
    val dealerState: String,
    val dealerDist: String,
    val dealerCity: String,
    val dealerPinCode: String,
    val dealerNumber: String,
    val addedBy: Int,
    val billDetails: String,
    val warrantyPhoto: String,
    val sellingPrice: String,
    val emptStr: String,
    val cresp: Cresp,
    val selectedProd: SelectedProd,
    val latitude: String,
    val longitude: String,
    val geolocation: String,
    val dealerCategory: String
)

data class Cresp(
    val custIdForProdInstall: String,
    val modelForProdInstall: String,
    val errorCode: Int,
    val errorMsg: String,
    val statusType: Int,
    val balance: String,
    val currentPoints: String,
    val couponPoints: String,
    val promotionPoints: String,
    val transactId: String,
    val schemePoints: String,
    val basePoints: String,
    val clubPoints: String,
    val scanDate: String,
    val scanStatus: String,
    val copuonCode: String,
    val bitEligibleScratchCard: Boolean,
    val pardId: Int,
    val partNumber: String,
    val partName: String,
    val couponCode: String,
    val skuDetail: String,
    val purchaseDate: String,
    val categoryId: String,
    val category: String,
    val anomaly: Int,
    val warranty: String
)

data class SelectedProd(
    val specs: String,
    val pointsFormat: String,
    val product: String,
    val productName: String,
    val productCategory: String,
    val productCode: String,
    val points: Int,
    val imageUrl: String,
    val userId: String,
    val productId: String,
    val paytmMobileNo: String
)